---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ServiceAccounts
  - ./serviceaccounts/mysql.yaml

  # Secrets
  - ./secrets/mysql-secret.yaml

  # PersistentVolumeClaims
  - ./persistentvolumeclaims/mysql-pv-claim.yaml

  # Deployments
  - ./deployments/mysql.yaml

  # Services
  - ./services/mysql.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: mysql
    newName: gcr.io/ml-pipeline/mysql
    newTag: "5.7"
